import type { Lang } from '~/utils/proposal'

const dict = {
  pt: {
    hello: 'Olá',
    subtitle: 'Sua proposta de viagem',
    subtitleAereo: 'Sua cotação de passagens',
    from: 'Saindo de',
    chooseFlight: (leg: string) => `${leg}: escolha seu voo`,
    mixTag: 'Personalize',
    mixTitle: 'Monte do seu jeito',
    mixDesc: 'Combine voos, hotel e passeios de opções diferentes',
    mixName: 'Minha combinação',
    mixHint: 'Toque para escolher cada voo e hotel, e adicione os passeios que quiser. O total é recalculado na hora.',
    chooseHotel: 'Escolha sua hospedagem',
    addTours: 'Adicione os passeios que quiser:',
    add: 'Adicionar',
    added: 'Adicionado',
    cheapest: 'Mais barato',
    fastest: 'Mais rápido',
    lineFlight: (leg: string) => (leg === 'Ida' ? 'Voo de ida' : leg === 'Volta' ? 'Voo de volta' : `Voo · ${leg}`),
    lineHotel: 'Hospedagem',
    lineTour: 'Passeio',
    lineTransfer: 'Transfer',
    linePackage: 'Pacote (preço fechado)',
    included2: 'incluído',
    taxesIncluded: 'taxas inclusas',
    departsFrom: 'Saída de',
    arrivesAt: 'Chegada em',
    connectionIn: 'Conexão em',
    arrives: 'chega',
    departs: 'sai',
    ofWait: 'de espera',
    fareShort: 'Tarifa',
    notIncludedShort: 'Não inclui',
    connectionsN: (n: number) => (n === 1 ? '1 conexão' : `${n} conexões`),
    fareTitle: 'Sua tarifa',
    navFare: 'Tarifa',
    fareIncluded: 'O que está incluído',
    fareChange: 'Remarcação',
    fareCancel: 'Cancelamento',
    fareCompare: 'Compare as tarifas',
    fareDiff: '+ diferença tarifária, se houver',
    fareFeatures: {
      personal: 'Artigo pessoal', carryon: 'Mala de mão (10kg)', checked: 'Mala despachada (23kg)', seat: 'Marcação de assento',
      meal: 'Refeição a bordo', miles: 'Acúmulo de milhas', priority: 'Embarque prioritário'
    },
    changeRule: { free: 'Sem taxa', fee: 'Com taxa', no: 'Não permitida' },
    cancelRule: { full: 'Reembolso total', fee: 'Reembolso com multa', credit: 'Crédito para nova viagem', no: 'Não reembolsável' },
    changeShort: { free: 'Sem taxa', fee: 'Com taxa', no: 'Não' },
    cancelShort: { full: 'Reembolso', fee: 'Com multa', credit: 'Crédito', no: 'Não' },
    feePerPerson: (v: string) => `${v} por pessoa`,
    tripType: 'Trecho',
    roundTrip: 'Ida e volta',
    oneWay: 'Somente ida',
    options: 'Opções',
    payTitle: 'Formas de pagamento',
    payPix: (pct: number) => `À vista no PIX · ${pct}% de desconto`,
    payInstallments: (n: number, v: string, free: boolean) => `ou ${n}x de ${v}${free ? ' sem juros' : ''} no cartão`,
    payUpTo: (n: number) => `ou em até ${n}x no cartão`,
    payShort: (n: number, v: string) => `ou ${n}x de ${v}`,
    cadasturTitle: 'Agência cadastrada no Ministério do Turismo',
    cadasturNo: 'Cadastur nº',
    verify: 'Verificar',
    summary: 'Resumo da viagem',
    dates: 'Datas',
    nights: 'noites',
    days: 'dias',
    travelers: 'Viajantes',
    traveler: 'viajante',
    travelersN: 'viajantes',
    duration: 'Duração',
    included: 'Incluído',
    chooseOption: 'Escolha sua opção',
    navOptions: 'Opções',
    navItinerary: 'Roteiro',
    recommended: 'Recomendada',
    flights: 'Voos',
    hotel: 'Hospedagem',
    itinerary: 'Roteiro dia a dia',
    tours: 'Passeios',
    transfers: 'Transfers',
    investment: 'Investimento',
    conditions: 'Condições',
    validity: 'Validade da proposta',
    validUntil: 'Válida até',
    daysLeft: (n: number) => (n === 0 ? 'Último dia!' : n === 1 ? 'Falta 1 dia' : `Faltam ${n} dias`),
    expired: 'Esta proposta expirou. Fale com a gente para atualizarmos os valores.',
    reserve: 'Quero reservar',
    talk: 'Falar com a Oasis Trip',
    total: 'Total',
    perPerson: 'por pessoa',
    subtotal: 'Subtotal',
    discount: 'Descontos',
    fees: 'Taxas',
    day: 'Dia',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    room: 'Quarto',
    board: 'Regime',
    baggage: 'Bagagem',
    notes: 'Observações',
    whatIncluded: 'O que está incluído',
    notIncluded: 'Não incluído',
    seeMore: 'Ver detalhes',
    seeLess: 'Ver menos',
    passengers: 'passageiros',
    reservedTitle: 'Recebemos seu pedido! 🎉',
    reservedText: 'Nossa equipe vai entrar em contato em breve para confirmar sua reserva. Se preferir, chame agora no WhatsApp.',
    confirmReserve: (o: string) => `Confirmar interesse na ${o}?`,
    confirmBtn: 'Sim, quero reservar',
    cancel: 'Voltar',
    noPayment: 'Nenhum pagamento será cobrado agora.',
    alreadyReserved: 'Você já solicitou a reserva desta proposta.',
    accepted: 'Proposta aceita — obrigado pela confiança!',
    waHello: (name: string, code: string) => `Olá! Sou ${name} e tenho uma dúvida sobre a proposta ${code}.`,
    waReserve: (name: string, code: string, opt: string) => `Olá! Sou ${name} e quero reservar a proposta ${code} (${opt}). 🙌`,
    madeBy: 'Proposta preparada por',
    loading: 'Preparando sua viagem…',
    notFound: 'Proposta não encontrada',
    notFoundText: 'Verifique o link recebido ou fale com a Oasis Trip.',
    // Avaliação
    rvBannerTitle: 'Como foi sua viagem?',
    rvBannerText: 'Conte pra gente em 1 minutinho — sua opinião é muito importante!',
    rvBannerBtn: 'Avaliar minha viagem',
    rvEyebrow: 'Avaliação da viagem',
    rvTitle: (name: string, city: string) => `${name ? name + ', c' : 'C'}omo foi sua viagem${city ? ' para ' + city : ''}?`,
    rvStars: ['Muito ruim', 'Ruim', 'Regular', 'Muito boa', 'Incrível!'],
    rvTapStars: 'Toque nas estrelas para dar sua nota',
    rvLiked: 'O que você mais gostou?',
    rvImprove: 'O que podemos melhorar?',
    rvTags: { atendimento: 'Atendimento', hotel: 'Hotel', passeios: 'Passeios', voos: 'Voos', roteiro: 'Roteiro', preco: 'Custo-benefício', transfers: 'Transfers' },
    rvComment: 'Conte um pouco da sua experiência',
    rvCommentPh: 'O que mais marcou sua viagem?',
    rvAllow: 'Autorizo a Oasis Trip a compartilhar meu depoimento',
    rvSend: 'Enviar avaliação',
    rvThanksTitle: (name: string) => `Obrigado${name ? ', ' + name : ''}! 💛`,
    rvThanksHappy: 'Ficamos muito felizes que sua viagem foi especial. Que tal ajudar outros viajantes a nos conhecerem?',
    rvThanksSad: 'Sentimos muito que a experiência não foi como esperado. Nossa equipe vai entrar em contato para entender e melhorar.',
    rvGoogle: 'Avaliar no Google',
    rvFollow: 'Seguir no Instagram',
    rvNextTrip: 'Planejar minha próxima viagem',
    rvTalk: 'Falar com a Oasis Trip',
    rvAlready: 'Você já avaliou esta viagem. Pode atualizar sua avaliação quando quiser.',
    rvEdit: 'Editar avaliação',
    waNextTrip: (name: string) => `Olá! Sou ${name} e quero planejar minha próxima viagem com a Oasis Trip! ✈️`,
    waSad: (name: string, code: string) => `Olá! Sou ${name} (proposta ${code}) e gostaria de conversar sobre minha viagem.`
  },
  es: {
    hello: 'Hola',
    subtitle: 'Tu propuesta de viaje',
    subtitleAereo: 'Tu cotización de pasajes',
    from: 'Saliendo de',
    chooseFlight: (leg: string) => `${leg}: elige tu vuelo`,
    mixTag: 'Personaliza',
    mixTitle: 'Arma tu viaje',
    mixDesc: 'Combina vuelos, hotel y paseos de distintas opciones',
    mixName: 'Mi combinación',
    mixHint: 'Toca para elegir cada vuelo y hotel, y agrega los paseos que quieras. El total se recalcula al instante.',
    chooseHotel: 'Elige tu alojamiento',
    addTours: 'Agrega los paseos que quieras:',
    add: 'Agregar',
    added: 'Agregado',
    cheapest: 'Más barato',
    fastest: 'Más rápido',
    lineFlight: (leg: string) => (leg === 'Ida' ? 'Vuelo de ida' : leg === 'Vuelta' ? 'Vuelo de vuelta' : `Vuelo · ${leg}`),
    lineHotel: 'Alojamiento',
    lineTour: 'Paseo',
    lineTransfer: 'Traslado',
    linePackage: 'Paquete (precio cerrado)',
    included2: 'incluido',
    taxesIncluded: 'tasas incluidas',
    departsFrom: 'Salida de',
    arrivesAt: 'Llegada a',
    connectionIn: 'Conexión en',
    arrives: 'llega',
    departs: 'sale',
    ofWait: 'de espera',
    fareShort: 'Tarifa',
    notIncludedShort: 'No incluye',
    connectionsN: (n: number) => (n === 1 ? '1 conexión' : `${n} conexiones`),
    fareTitle: 'Tu tarifa',
    navFare: 'Tarifa',
    fareIncluded: 'Qué incluye',
    fareChange: 'Cambios',
    fareCancel: 'Cancelación',
    fareCompare: 'Compara las tarifas',
    fareDiff: '+ diferencia tarifaria, si la hay',
    fareFeatures: {
      personal: 'Artículo personal', carryon: 'Equipaje de mano (10kg)', checked: 'Maleta facturada (23kg)', seat: 'Selección de asiento',
      meal: 'Comida a bordo', miles: 'Acumulación de millas', priority: 'Embarque prioritario'
    },
    changeRule: { free: 'Sin cargo', fee: 'Con cargo', no: 'No permitido' },
    cancelRule: { full: 'Reembolso total', fee: 'Reembolso con multa', credit: 'Crédito para un nuevo viaje', no: 'No reembolsable' },
    changeShort: { free: 'Sin cargo', fee: 'Con cargo', no: 'No' },
    cancelShort: { full: 'Reembolso', fee: 'Con multa', credit: 'Crédito', no: 'No' },
    feePerPerson: (v: string) => `${v} por persona`,
    tripType: 'Tramo',
    roundTrip: 'Ida y vuelta',
    oneWay: 'Solo ida',
    options: 'Opciones',
    payTitle: 'Formas de pago',
    payPix: (pct: number) => `Al contado (PIX/transferencia) · ${pct}% de descuento`,
    payInstallments: (n: number, v: string, free: boolean) => `o ${n} cuotas de ${v}${free ? ' sin intereses' : ''} con tarjeta`,
    payUpTo: (n: number) => `o hasta ${n} cuotas con tarjeta`,
    payShort: (n: number, v: string) => `o ${n} cuotas de ${v}`,
    cadasturTitle: 'Agencia registrada en el Ministerio de Turismo de Brasil',
    cadasturNo: 'Cadastur nº',
    verify: 'Verificar',
    summary: 'Resumen del viaje',
    dates: 'Fechas',
    nights: 'noches',
    days: 'días',
    travelers: 'Viajeros',
    traveler: 'viajero',
    travelersN: 'viajeros',
    duration: 'Duración',
    included: 'Incluido',
    chooseOption: 'Elige tu opción',
    navOptions: 'Opciones',
    navItinerary: 'Itinerario',
    recommended: 'Recomendada',
    flights: 'Vuelos',
    hotel: 'Alojamiento',
    itinerary: 'Itinerario día a día',
    tours: 'Paseos',
    transfers: 'Traslados',
    investment: 'Inversión',
    conditions: 'Condiciones',
    validity: 'Validez de la propuesta',
    validUntil: 'Válida hasta',
    daysLeft: (n: number) => (n === 0 ? '¡Último día!' : n === 1 ? 'Falta 1 día' : `Faltan ${n} días`),
    expired: 'Esta propuesta expiró. Escríbenos para actualizar los valores.',
    reserve: 'Quiero reservar',
    talk: 'Hablar con Oasis Trip',
    total: 'Total',
    perPerson: 'por persona',
    subtotal: 'Subtotal',
    discount: 'Descuentos',
    fees: 'Tasas',
    day: 'Día',
    checkIn: 'Check-in',
    checkOut: 'Check-out',
    room: 'Habitación',
    board: 'Régimen',
    baggage: 'Equipaje',
    notes: 'Observaciones',
    whatIncluded: 'Qué incluye',
    notIncluded: 'No incluye',
    seeMore: 'Ver detalles',
    seeLess: 'Ver menos',
    passengers: 'pasajeros',
    reservedTitle: '¡Recibimos tu solicitud! 🎉',
    reservedText: 'Nuestro equipo te contactará pronto para confirmar tu reserva. Si prefieres, escríbenos ahora por WhatsApp.',
    confirmReserve: (o: string) => `¿Confirmar interés en la ${o}?`,
    confirmBtn: 'Sí, quiero reservar',
    cancel: 'Volver',
    noPayment: 'No se cobrará ningún pago ahora.',
    alreadyReserved: 'Ya solicitaste la reserva de esta propuesta.',
    accepted: 'Propuesta aceptada — ¡gracias por tu confianza!',
    waHello: (name: string, code: string) => `¡Hola! Soy ${name} y tengo una duda sobre la propuesta ${code}.`,
    waReserve: (name: string, code: string, opt: string) => `¡Hola! Soy ${name} y quiero reservar la propuesta ${code} (${opt}). 🙌`,
    madeBy: 'Propuesta preparada por',
    loading: 'Preparando tu viaje…',
    notFound: 'Propuesta no encontrada',
    notFoundText: 'Verifica el enlace recibido o escríbele a Oasis Trip.',
    // Evaluación
    rvBannerTitle: '¿Cómo fue tu viaje?',
    rvBannerText: 'Cuéntanos en 1 minutito — ¡tu opinión es muy importante!',
    rvBannerBtn: 'Evaluar mi viaje',
    rvEyebrow: 'Evaluación del viaje',
    rvTitle: (name: string, city: string) => `${name ? name + ', ¿c' : '¿C'}ómo fue tu viaje${city ? ' a ' + city : ''}?`,
    rvStars: ['Muy malo', 'Malo', 'Regular', 'Muy bueno', '¡Increíble!'],
    rvTapStars: 'Toca las estrellas para dar tu nota',
    rvLiked: '¿Qué fue lo que más te gustó?',
    rvImprove: '¿Qué podemos mejorar?',
    rvTags: { atendimento: 'Atención', hotel: 'Hotel', passeios: 'Paseos', voos: 'Vuelos', roteiro: 'Itinerario', preco: 'Costo-beneficio', transfers: 'Traslados' },
    rvComment: 'Cuéntanos un poco de tu experiencia',
    rvCommentPh: '¿Qué fue lo que más te marcó del viaje?',
    rvAllow: 'Autorizo a Oasis Trip a compartir mi testimonio',
    rvSend: 'Enviar evaluación',
    rvThanksTitle: (name: string) => `¡Gracias${name ? ', ' + name : ''}! 💛`,
    rvThanksHappy: 'Nos alegra mucho que tu viaje haya sido especial. ¿Nos ayudas a que otros viajeros nos conozcan?',
    rvThanksSad: 'Lamentamos que la experiencia no haya sido la esperada. Nuestro equipo te contactará para entender y mejorar.',
    rvGoogle: 'Evaluar en Google',
    rvFollow: 'Seguir en Instagram',
    rvNextTrip: 'Planear mi próximo viaje',
    rvTalk: 'Hablar con Oasis Trip',
    rvAlready: 'Ya evaluaste este viaje. Puedes actualizar tu evaluación cuando quieras.',
    rvEdit: 'Editar evaluación',
    waNextTrip: (name: string) => `¡Hola! Soy ${name} y quiero planear mi próximo viaje con Oasis Trip. ✈️`,
    waSad: (name: string, code: string) => `¡Hola! Soy ${name} (propuesta ${code}) y me gustaría conversar sobre mi viaje.`
  }
}

// Valores sugeridos no admin (em português) traduzidos para o cliente em espanhol
const values: Record<string, string> = {
  'Direto': 'Directo', '1 escala': '1 escala', '2 escalas': '2 escalas', '1 conexão': '1 conexión', '2 conexões': '2 conexiones',
  'Artigo pessoal': 'Artículo personal', 'Mala de mão 10kg': 'Equipaje de mano 10kg',
  '1 mala despachada 23kg': '1 maleta facturada 23kg', '2 malas despachadas 23kg': '2 maletas facturadas 23kg',
  'Mala de mão + 1 despachada 23kg': 'Equipaje de mano + 1 facturada 23kg',
  'Sem refeição': 'Sin comidas', 'Café da manhã': 'Desayuno', 'Meia pensão': 'Media pensión',
  'Pensão completa': 'Pensión completa', 'All inclusive': 'Todo incluido',
  'Privativo': 'Privado', 'Compartilhado': 'Compartido', 'Van privativa': 'Van privada', 'Carro executivo': 'Auto ejecutivo', 'Ônibus': 'Bus',
  'Econômica': 'Económica', 'Econômica Light': 'Económica Light', 'Econômica Standard': 'Económica Standard',
  'Econômica Plus': 'Económica Plus', 'Executiva': 'Ejecutiva',
  'Taxas de embarque e aeroportuárias': 'Tasas de embarque y aeroportuarias', 'Taxa de emissão': 'Cargo de emisión',
  'Taxas de embarque + taxa de emissão': 'Tasas de embarque + cargo de emisión', 'Taxa de turismo local': 'Tasa turística local',
  'Taxas e impostos': 'Tasas e impuestos',
  'Ida': 'Ida', 'Volta': 'Vuelta', 'Trecho 3': 'Tramo 3', 'Trecho 4': 'Tramo 4',
  'Aeroporto': 'Aeropuerto', 'Quarto duplo': 'Habitación doble', 'Quarto triplo': 'Habitación triple', 'Luxo': 'Lujo', 'Suíte': 'Suite', 'Vista mar': 'Vista al mar'
}

// Palavras dos nomes de opção sugeridos (ex.: "Opção 1 · Mais rápida" → "Opción 1 · Más rápida")
const optionWords: [RegExp, string][] = [
  [/\bOpção\b/g, 'Opción'], [/\bOpções\b/g, 'Opciones'], [/\bVoo direto\b/gi, 'Vuelo directo'], [/\bVoo\b/g, 'Vuelo'],
  [/\bMais econômica\b/gi, 'Más económica'], [/\bMais barata\b/gi, 'Más barata'], [/\bMais rápida\b/gi, 'Más rápida'],
  [/\bMais confortável\b/gi, 'Más cómoda'], [/\bEconômica\b/g, 'Económica'], [/\bEssencial\b/g, 'Esencial'],
  [/\bRecomendada\b/g, 'Recomendada'], [/\bsem escalas\b/gi, 'sin escalas'], [/\bcom bagagem\b/gi, 'con equipaje']
]
/** Traduz um nome de opção escrito em português, se a proposta for em espanhol */
export const optionNameFor = (name: string, lang: Lang) =>
  lang === 'es' ? optionWords.reduce((acc, [re, to]) => acc.replace(re, to), name || '') : name

export const useProposalText = (lang: MaybeRefOrGetter<Lang>) => {
  const t = computed(() => dict[toValue(lang)] || dict.pt)
  const v = (s: string) => (toValue(lang) === 'es' ? values[s] || s : s)
  const on = (name: string) => optionNameFor(name, toValue(lang))
  return { t, v, on }
}
